### ISSUE TITLE
Proper syntax for SL's private network configuration?

### ISSUE THREAD

**Issue by lonniev** [audiolize/vagrant-softlayer#40]
Probably just a failure to RTFM but I cannot get the SL provider to configure a private network with statically assigned IP addresses. I see that a private network address does get assigned to eth0 (and a public one to eth1) but the address assigned is not what I specify in the Vagrant file.

Here is the snippet from the Vagrantfile:

    config.hostmanager.enabled = true
    config.hostmanager.ignore_private_ip = false
    config.hostmanager.include_offline = true

    config.vm.define "sl-ubuntu-host1", primary: true do | vmh |

      vmh.vm.hostname = "host1"

      vmh.vm.provider :softlayer do |sl, vmh_override|
        sl.hostname                  = vmh.vm.hostname
        vmh_override.vm.network "private_network", type: "static", ip: "10.0.0.10", auto_config: true
      end if Vagrant.has_plugin?("SoftLayer")

      vmh.vm.network "public_network", bridge: 'eth1'
      vmh.hostmanager.aliases = %w(proxy.internal.net)
      vmh.vm.usable_port_range          = 2200..6000

    end

The "hostmanager" lines are there for the hostmanager plugin to modify the /etc/hosts file on each of the VMs this Vagrantfile provisions. Hostmanager does update the hosts file with the IPs that I specify. However, the instance has a dhcp-assigned 10.* address which is viewable with ifconfig and that is not the one requested.

There are no other explicit vm.network statements in the file; nevertheless, something is overriding my statement and configuring the private network on eth0 with DHCP.

**Comment by ju2wheels** [comment]
closing, assuming the above worked out ok, if not reopen or let us know.

**Comment by lonniev** [comment]
np. I haven't worked with the SL vagrants for a few months now. I hope to get back to them this Spring.
