### ISSUE TITLE
vagrant plugin installing previous version

### ISSUE THREAD

**Issue by vincenthuynh** [audiolize/vagrant-softlayer#53]
Is anyone else noticing that vagrant plugin install is installing the previous version? We are currently at v0.4.1

````
> vagrant plugin install vagrant-softlayer --debug
 INFO global: Vagrant version: 1.7.1
 INFO global: Ruby version: 2.0.0
 INFO global: RubyGems version: 2.0.14
 INFO global:   - bundler = 1.7.9
 INFO global:   - configparser = 0.1.3
 INFO global:   - json = 1.8.2
 INFO global:   - mime-types = 1.25.1
 INFO global:   - rdoc = 4.2.0
 INFO global:   - rest-client = 1.6.8
 INFO global:   - softlayer_api = 3.0.2
 INFO global:   - vagrant-share = 1.1.4
 INFO global:   - vagrant-softlayer = 0.4.0

Installing the 'vagrant-softlayer' plugin. This can take a few minutes...
 INFO interface: success: Installed the plugin 'vagrant-softlayer (0.4.0)'!
Installed the plugin 'vagrant-softlayer (0.4.0)'!
````

**Comment by ju2wheels** [comment]
Hi @vincenthuynh, this shouldnt be a problem if you are on a fresh setup, the latest one just hasnt been pushed to rubygems yet. `0.4.1` was just a minor bug fix release to pin us to `softlayer_api` minimum version of `3.0.1` to fix an upstream bug and to fix a minor bug in one of the `contrib` scripts. If you have a setup thats not new you just need to update your vagrant plugins and ensure you remove older `softlayer_api` gems from your `.vagrant.d` directory just as a precaution. But other than this theres no major difference in `0.4.0` and `0.4.1` in functionality or code changes. You are on the latest `softlayer_api` so you should be good.

**Comment by vincenthuynh** [comment]
Sounds good. I'll check for those things. Thanks!
