### ISSUE TITLE
Add Link to DNS Hosting by Softlayer

### ISSUE THREAD

**Issue by lonniev** [audiolize/vagrant-softlayer#55]
> If the DNS zone of the configured domain is hosted by SoftLayer, you can automatically manage it.

Can someone add a "cross selling" link here? That is, add the phrase:

> If you would like to have a DNS hosted by SoftLayer so that vagrant-softlayer will create DNS entries for you, then click HERE.

**Comment by ju2wheels** [comment]
Added links to SL KnowledgeLayer.

**Comment by lonniev** [comment]
Thank you.
